# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://visateam.github.io
baseurl: 
title: Visa Team
email: your-email@domain.com
author: Visa Team
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2017 Visa Team. All Rights Reserved.'
credits: 'Credits: This website was made by Barbara.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: instagram
    url: 
  - title: linkedin
    url: 
